# Generated by Django 4.0.1 on 2022-04-01 13:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255)),
                ('data_fato', models.DateField()),
                ('data_registro', models.DateField()),
                ('local_registro', models.CharField(max_length=255)),
                ('meios_empregados', models.CharField(max_length=255)),
                ('natureza_crime', models.CharField(choices=[('1', 'ESTELIONATO'), ('2', 'TENTATIVA DE ESTELIONATO'), ('3', 'FURTO'), ('4', 'INVASAO DE DISPOSITIVO'), ('5', 'AMEAÇA'), ('6', 'OUTROS FATOS ATIPICOS')], max_length=1)),
                ('situacao_bo', models.CharField(choices=[('1', 'Arquivado'), ('2', 'Delegado'), ('3', 'Outras Delegacias'), ('4', 'Aguardando em Cartorio'), ('5', 'Instaurados IP'), ('6', 'Instaurados TCO')], max_length=1)),
                ('obs', models.TextField()),
                ('data_insercao', models.DateField(default=datetime.date.today)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Chave_pix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pix', models.CharField(blank=True, max_length=255)),
                ('instituicao', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Conta_corrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=255)),
                ('agencia', models.CharField(blank=True, max_length=255)),
                ('instituicao', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=255)),
                ('rg', models.CharField(blank=True, max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Envolvido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('1', 'Infrator'), ('2', 'Vítima')], max_length=1)),
                ('telefone_golpe', models.CharField(blank=True, max_length=255)),
                ('valorpix', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('valorcc', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('bo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocorrencia.bo')),
                ('chave_pix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ocorrencia.chave_pix')),
                ('conta_corrente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ocorrencia.conta_corrente')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocorrencia.pessoa')),
            ],
        ),
    ]
