# Generated by Django 4.0.1 on 2022-02-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bo',
            name='natureza_crime',
            field=models.CharField(choices=[('1', 'ESTELIONATO'), ('2', 'ENTATIVA DE ESTELIONATO'), ('3', 'FURTO'), ('4', 'INVASAO DE DISPOSITIVO'), ('5', 'AMEAÇA'), ('6', 'OUTROS FATOS ATIPICOS')], max_length=1),
        ),
    ]
