# Generated by Django 4.0.1 on 2022-05-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bo',
            name='natureza_crime',
            field=models.ManyToManyField(related_name='naturezas', to='ocorrencia.Natureza'),
        ),
        migrations.AlterField(
            model_name='bo',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chave_pix',
            name='pix',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
