# Generated by Django 4.0.1 on 2022-04-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bo',
            name='valor_total',
        ),
    ]
