# Generated by Django 4.0.1 on 2022-04-01 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0002_remove_bo_valor_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envolvido',
            old_name='valorcc',
            new_name='valor_cc',
        ),
        migrations.RenameField(
            model_name='envolvido',
            old_name='valorpix',
            new_name='valor_pix',
        ),
    ]
