# Generated by Django 4.0.1 on 2022-04-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0003_rename_valorcc_envolvido_valor_cc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envolvido',
            name='valor_cc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='envolvido',
            name='valor_pix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
