# Generated by Django 4.0.1 on 2022-04-07 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0004_alter_envolvido_valor_cc_alter_envolvido_valor_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envolvido',
            name='bo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bos', to='ocorrencia.bo'),
        ),
        migrations.AlterField(
            model_name='envolvido',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='ocorrencia.pessoa'),
        ),
    ]
