# Generated by Django 4.0.1 on 2022-04-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0005_alter_envolvido_bo_alter_envolvido_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envolvido',
            name='valor_cc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='envolvido',
            name='valor_pix',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
