# Generated by Django 4.0.1 on 2022-04-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0006_alter_envolvido_valor_cc_alter_envolvido_valor_pix'),
    ]

    operations = [
        migrations.AddField(
            model_name='envolvido',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
