# Generated by Django 4.0.1 on 2022-04-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0007_envolvido_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='bo',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
