# Generated by Django 4.0.1 on 2022-04-13 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0008_bo_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envolvido',
            name='chave_pix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pixs', to='ocorrencia.chave_pix'),
        ),
    ]
