# Generated by Django 4.0.1 on 2022-04-18 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0009_alter_envolvido_chave_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envolvido',
            name='conta_corrente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cc', to='ocorrencia.conta_corrente'),
        ),
    ]
